---
apiVersion: v1
kind: Service
metadata:
  annotations:
    derrick.service.type: nodeport
    derrick.version: 0.0.20
  labels:
    derrick.service: aks-demo
  name: aks-demo
spec:
  ports:
  - name: "3000"
    port: 3000
    targetPort: 3000
  selector:
    derrick.service: aks-demo
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    derrick.version: 0.0.20
  labels:
    derrick.service: aks-demo
  name: aks-demo
spec:
  replicas: 1
  template:
    metadata:
      labels:
        derrick.service: aks-demo
    spec:
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/derrick_demo/derrick_demo:4.1
        name: web
        ports:
        - containerPort: 3000